### ISSUE TITLE
CI on k8s 1.15+ is failing to build kind images

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-release-tools#38]
It seems like latest 1.15 branch requires cgo, which we don't have enabled:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-csi-1-14-on-kubernetes-1-15/1186364041350615041/build-log.txt

```
ERROR: /home/prow/go/pkg/csiprow.Uakw8FT0JH/src/kubernetes/vendor/golang.org/x/sys/unix/BUILD:3:1: in @io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect[pure="off",static="auto",msan="auto",race="auto",goos="auto",goarch="auto",linkmode="normal"] aspect on go_library rule //vendor/golang.org/x/sys/unix:go_default_library: 
Traceback (most recent call last):
	File "/home/prow/go/pkg/csiprow.Uakw8FT0JH/src/kubernetes/vendor/golang.org/x/sys/unix/BUILD", line 3
		@io_bazel_rules_go//go/private:rules/aspect.bzl%go_archive_aspect(...)
	File "/root/.cache/bazel/_bazel_root/dbb3a0bf0fb768dd6a59e5dab737c453/external/io_bazel_rules_go/go/private/rules/aspect.bzl", line 59, in _go_archive_aspect_impl
		go.archive(go, source = source)
	File "/root/.cache/bazel/_bazel_root/dbb3a0bf0fb768dd6a59e5dab737c453/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 92, in go.archive
		cgo_configure(go, srcs = (((((split.go + split.c...), <5 more arguments>)
	File "/root/.cache/bazel/_bazel_root/dbb3a0bf0fb768dd6a59e5dab737c453/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 101, in cgo_configure
		fail("Go toolchain does not support c...")
Go toolchain does not support cgo
ERROR: Analysis of target '//cmd/kubelet:kubelet' failed; build aborted: Analysis of target '//vendor/golang.org/x/sys/unix:go_default_library' failed; build aborted
```

Maybe we can also take this opportunity to upgrade to Go 1.13+?

**Comment by msau42** [comment]
/kind failing-test

@pohly do you have time to look into this?

**Comment by msau42** [comment]
Looks like https://github.com/kubernetes-sigs/kind/pull/963 fixes it. So we either need to upgrade our kind again, or don't use the bazel build method

**Comment by msau42** [comment]
testing in https://github.com/kubernetes-csi/csi-driver-host-path/pull/106
